//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int MoveId { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public int MoveNumber { get; set; }
        public int RowIndex { get; set; }
        public int ColumnIndex { get; set; }
        public string Symbol { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
